export const ADMIN_LAY_DS_NGUOI_DUNG_CHUA_GHI_DANH =
  "ADMIN_LAY_DS_NGUOI_DUNG_CHUA_GHI_DANH";

export const ADMIN_LAY_DS_NGUOI_DUNG_CHO_XAC_THUC =
  "ADMIN_LAY_DS_NGUOI_DUNG_CHO_XAC_THUC";

export const ADMIN_LAY_THONG_TIN_KHOA_HOC = "ADMIN_LAY_THONG_TIN_KHOA_HOC";

export const ADMIN_CAP_NHAT_THONG_TIN_KHOA_HOC="ADMIN_CAP_NHAT_THONG_TIN_KHOA_HOC"
export const ADMIN_TIM_KIEM_KHOA_HOC="ADMIN_TIM_KIEM_KHOA_HOC"