export const ADMIN_THEM_NGUOI_DUNG = "ADMIN_THEM_NGUOI_DUNG";

export const ADMIN_XOA_NGUOI_DUNG = "ADMIN_XOA_NGUOI_DUNG";

export const ADMIN_CAPNHAT_THONGTIN_NGUOIDUNG =
  "ADMIN_CAPNHAT_THONGTIN_NGUOIDUNG";

export const ADMIN_CHI_TIET_THONG_TIN_NGUOI_DUNG =
  "ADMIN_CHI_TIET_THONG_TIN_NGUOI_DUNG";
