export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const DANG_KY_ACTION = "DANG_KY_ACTION";

export const THONG_TIN_NGUOI_DUNG_ACTION = "THONG_TIN_NGUOI_DUNG_ACTION";

export const LAY_DANH_SACH_NGUOI_DUNG =
  "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_DATA =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_DATA";
export const LAY_MA_LOAI_NGUOI_DUNG = "LAY_MA_LOAI_NGUOI_DUNG";
export const CAP_NHAT_THONG_TIN_NGUOI_DUNG_ACTION =
  "CAP_NHAT_THONG_TIN_NGUOI_DUNG_ACTION";
