export const LAY_DANH_SACH_KHOA_HOC_ACTION = "LAY_DANH_SACH_KHOA_HOC_ACTION";
export const CHI_TIET_KHOA_HOC_DA_DANG_KY = "CHI_TIET_KHOA_HOC_DA_DANG_KY";
export const CAP_NHAT_KHOA_HOC = "CAP_NHAT_KHOA_HOC";

