export const LAY_DANH_SACH_KHOA_HOC_ACTION = "LAY_DANH_SACH_KHOA_HOC_ACTION";

export const CHI_TIET_KHOA_HOC_DA_DANG_KY = "CHI_TIET_KHOA_HOC_DA_DANG_KY";

export const XOA_KHOA_HOC_DA_DANG_KY = "XOA_KHOA_HOC_DA_DANG_KY";
