export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const DANG_KY_ACTION = "DANG_KY_ACTION";

export const THONG_TIN_NGUOI_DUNG_ACTION = "THONG_TIN_NGUOI_DUNG_ACTION";

export const LAY_MA_LOAI_NGUOI_DUNG = "LAY_MA_LOAI_NGUOI_DUNG";
export const CAP_NHAT_THONG_TIN_NGUOI_DUNG_ACTION =
  "CAP_NHAT_THONG_TIN_NGUOI_DUNG_ACTION";
